{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyPgR5P4uq5rztudu6lJ2Cgg",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/ngocthi12123-cloud/TNTSMARTFARE/blob/main/Untitled4.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "fRJo_5K3Tlpb"
      },
      "outputs": [],
      "source": [
        "# copy từ app5\n",
        "# CÓ THỂ SỬ DỤNG\n",
        "# Tạo trafic fake nâng cấp hơn\n",
        "# app9 ổn hơn tất cả còn lại\n",
        "import streamlit as st\n",
        "from streamlit_folium import st_folium\n",
        "import folium\n",
        "import requests\n",
        "import numpy as np\n",
        "import skfuzzy as fuzz\n",
        "from skfuzzy import control as ctrl\n",
        "from geopy.geocoders import Nominatim\n",
        "from datetime import datetime\n",
        "import math\n",
        "\n",
        "# ============================================================\n",
        "# 1. CẤU HÌNH TRANG\n",
        "# ============================================================\n",
        "st.set_page_config(\n",
        "    page_title=\"TNT SMARTFARE\",\n",
        "    layout=\"wide\",\n",
        "    page_icon=\"💎\",\n",
        "    initial_sidebar_state=\"collapsed\"\n",
        ")\n",
        "# Khởi tạo giá trị mặc định để tránh lỗi \"variable not defined\"\n",
        "dist = 0\n",
        "# ============================================================\n",
        "# 2. CSS PREMIUM DARK + GLASSMORPHISM (Navy + Gold)\n",
        "# ============================================================\n",
        "st.markdown(\"\"\"\n",
        "<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n",
        "<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n",
        "<link href=\"https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&family=Playfair+Display:wght@700;800;900&display=swap\" rel=\"stylesheet\">\n",
        "<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css\">\n",
        "\n",
        "<style>\n",
        ":root {\n",
        "    --navy-900: #060b1f;\n",
        "    --navy-800: #0a1330;\n",
        "    --navy-700: #111c44;\n",
        "    --navy-600: #1a2655;\n",
        "    --gold: #f5c842;\n",
        "    --gold-bright: #ffd86b;\n",
        "    --gold-deep: #b8860b;\n",
        "    --blue-electric: #3b82f6;\n",
        "    --blue-glow: #60a5fa;\n",
        "    --text-primary: #f8fafc;\n",
        "    --text-secondary: #cbd5e1;\n",
        "    --text-muted: #94a3b8;\n",
        "    --glass: rgba(255, 255, 255, 0.06);\n",
        "    --glass-border: rgba(255, 255, 255, 0.12);\n",
        "    --gold-grad: linear-gradient(135deg, #f5c842 0%, #ffd86b 50%, #b8860b 100%);\n",
        "}\n",
        "\n",
        ".stApp {\n",
        "    background:\n",
        "        radial-gradient(ellipse at top left, rgba(59, 130, 246, 0.18) 0%, transparent 45%),\n",
        "        radial-gradient(ellipse at bottom right, rgba(245, 200, 66, 0.12) 0%, transparent 45%),\n",
        "        linear-gradient(180deg, #060b1f 0%, #0a1330 50%, #060b1f 100%);\n",
        "    color: var(--text-primary);\n",
        "    font-family: 'Plus Jakarta Sans', sans-serif;\n",
        "}\n",
        "\n",
        "#MainMenu, footer, header[data-testid=\"stHeader\"] { visibility: hidden; }\n",
        ".block-container { padding-top: 1.2rem; padding-bottom: 2rem; max-width: 1400px; }\n",
        "\n",
        ".hero-wrap {\n",
        "    position: relative;\n",
        "    background: linear-gradient(135deg, rgba(10, 19, 48, 0.9) 0%, rgba(17, 28, 68, 0.85) 100%);\n",
        "    border: 1px solid var(--glass-border);\n",
        "    border-radius: 24px;\n",
        "    padding: 32px 40px;\n",
        "    margin-bottom: 24px;\n",
        "    overflow: hidden;\n",
        "    backdrop-filter: blur(20px);\n",
        "    -webkit-backdrop-filter: blur(20px);\n",
        "    box-shadow: 0 20px 60px rgba(0, 0, 0, 0.4);\n",
        "}\n",
        ".hero-wrap::before {\n",
        "    content: '';\n",
        "    position: absolute; top: -50%; right: -10%;\n",
        "    width: 400px; height: 400px;\n",
        "    background: radial-gradient(circle, rgba(245, 200, 66, 0.25) 0%, transparent 70%);\n",
        "    filter: blur(40px);\n",
        "}\n",
        ".hero-wrap::after {\n",
        "    content: '';\n",
        "    position: absolute; bottom: -50%; left: -10%;\n",
        "    width: 400px; height: 400px;\n",
        "    background: radial-gradient(circle, rgba(59, 130, 246, 0.25) 0%, transparent 70%);\n",
        "    filter: blur(40px);\n",
        "}\n",
        ".hero-content { position: relative; z-index: 2; display: flex; justify-content: space-between; align-items: center; flex-wrap: wrap; gap: 20px; }\n",
        ".hero-title {\n",
        "    font-family: 'Playfair Display', serif;\n",
        "    font-size: 42px; font-weight: 900;\n",
        "    background: var(--gold-grad);\n",
        "    -webkit-background-clip: text;\n",
        "    background-clip: text;\n",
        "    -webkit-text-fill-color: transparent;\n",
        "    margin: 0; letter-spacing: -1px;\n",
        "    line-height: 1.1;\n",
        "}\n",
        ".hero-sub { font-size: 14px; color: var(--text-secondary); margin-top: 6px; letter-spacing: 0.5px; }\n",
        ".hero-badge {\n",
        "    display: inline-flex; align-items: center; gap: 8px;\n",
        "    background: rgba(245, 200, 66, 0.12);\n",
        "    border: 1px solid rgba(245, 200, 66, 0.4);\n",
        "    color: var(--gold-bright);\n",
        "    padding: 6px 14px; border-radius: 50px;\n",
        "    font-size: 11px; font-weight: 700; letter-spacing: 1.5px;\n",
        "    text-transform: uppercase; margin-bottom: 12px;\n",
        "}\n",
        ".hero-badge .dot {\n",
        "    width: 6px; height: 6px; border-radius: 50%;\n",
        "    background: var(--gold-bright);\n",
        "    box-shadow: 0 0 10px var(--gold-bright);\n",
        "    animation: pulse 1.8s ease-in-out infinite;\n",
        "}\n",
        "@keyframes pulse { 0%,100% { opacity: 1; transform: scale(1);} 50% { opacity: 0.5; transform: scale(1.4);} }\n",
        "\n",
        ".hero-stats { display: flex; gap: 28px; }\n",
        ".stat-item { text-align: right; }\n",
        ".stat-val { font-family: 'Playfair Display', serif; font-size: 24px; font-weight: 800; color: var(--gold-bright); }\n",
        ".stat-lbl { font-size: 11px; color: var(--text-muted); text-transform: uppercase; letter-spacing: 1.2px; }\n",
        "\n",
        ".panel-title {\n",
        "    font-size: 13px; font-weight: 700; color: var(--gold-bright);\n",
        "    text-transform: uppercase; letter-spacing: 2px;\n",
        "    margin-bottom: 16px; display: flex; align-items: center; gap: 10px;\n",
        "}\n",
        ".panel-title i { color: var(--gold); font-size: 16px; }\n",
        "\n",
        "[data-testid=\"stVerticalBlockBorderWrapper\"] {\n",
        "    background: var(--glass) !important;\n",
        "    border: 1px solid var(--glass-border) !important;\n",
        "    border-radius: 20px !important;\n",
        "    backdrop-filter: blur(16px);\n",
        "}\n",
        "/* Đổi màu chữ tiêu đề 'Điểm đón' và 'Điểm đến' */\n",
        "[data-testid=\"stWidgetLabel\"] p {\n",
        "    color: #f8fafc !important;\n",
        "    font-weight: 700 !important; /* Làm chữ đậm lên cho rõ */\n",
        "    text-shadow: 0px 0px 5px rgba(0,0,0,0.5); /* Thêm chút bóng cho nổi bật */\n",
        "}\n",
        "\n",
        "/* ĐOẠN ĐÃ SỬA */\n",
        ".stTextInput input, .stTextArea textarea {\n",
        "    background: #ffffff !important; /* Đổi nền sang trắng để hiện chữ đen */\n",
        "    border: 1px solid rgba(0, 0, 0, 0.1) !important;\n",
        "    color: #000000 !important; /* Đổi chữ sang đen */\n",
        "    border-radius: 12px !important;\n",
        "    padding: 12px 16px !important;\n",
        "    font-family: 'Plus Jakarta Sans', sans-serif !important;\n",
        "    font-weight: 500 !important;\n",
        "    transition: all 0.25s ease;\n",
        "}\n",
        "\n",
        "/* Đảm bảo khi focus vào ô cũng giữ màu đen */\n",
        ".stTextInput input:focus, .stTextArea textarea:focus {\n",
        "    border-color: var(--gold) !important;\n",
        "    box-shadow: 0 0 0 3px rgba(245, 200, 66, 0.15) !important;\n",
        "    background: #ffffff !important;\n",
        "    color: #000000 !important;\n",
        "}\n",
        "\n",
        ".stButton > button {\n",
        "    background: var(--gold-grad) !important;\n",
        "    color: var(--navy-900) !important;\n",
        "    border: none !important;\n",
        "    border-radius: 12px !important;\n",
        "    font-weight: 800 !important;\n",
        "    padding: 12px 24px !important;\n",
        "    font-family: 'Plus Jakarta Sans', sans-serif !important;\n",
        "    letter-spacing: 0.3px !important;\n",
        "    transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1) !important;\n",
        "    box-shadow: 0 6px 20px rgba(245, 200, 66, 0.25) !important;\n",
        "}\n",
        ".stButton > button:hover {\n",
        "    transform: translateY(-2px);\n",
        "    box-shadow: 0 10px 28px rgba(245, 200, 66, 0.45) !important;\n",
        "    filter: brightness(1.08);\n",
        "}\n",
        ".stButton > button[kind=\"secondary\"] {\n",
        "    background: rgba(255, 255, 255, 0.06) !important;\n",
        "    color: var(--text-primary) !important;\n",
        "    border: 1px solid var(--glass-border) !important;\n",
        "    box-shadow: none !important;\n",
        "}\n",
        ".stButton > button[kind=\"secondary\"]:hover {\n",
        "    background: rgba(255, 255, 255, 0.1) !important;\n",
        "    border-color: var(--gold) !important;\n",
        "}\n",
        "\n",
        "/* Đổi màu chữ của các tùy chọn chọn xe (Radio buttons) */\n",
        ".stRadio div[role=\"radiogroup\"] label p {\n",
        "    color: #f8fafc !important;\n",
        "    font-weight: 500 !important;\n",
        "}\n",
        "\n",
        ".stMarkdown h2, .stMarkdown h3, [data-testid=\"stHeading\"] {\n",
        "    color: var(--text-primary) !important;\n",
        "    font-family: 'Plus Jakarta Sans', sans-serif !important;\n",
        "}\n",
        "\n",
        "[data-testid=\"stAlertContainer\"] {\n",
        "    background: rgba(34, 197, 94, 0.1) !important;\n",
        "    border: 1px solid rgba(34, 197, 94, 0.3) !important;\n",
        "    color: #86efac !important;\n",
        "    border-radius: 12px !important;\n",
        "}\n",
        "\n",
        ".veh-grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 10px; margin-top: 10px; }\n",
        ".veh-card {\n",
        "    background: rgba(255, 255, 255, 0.04);\n",
        "    border: 1px solid var(--glass-border);\n",
        "    border-radius: 14px;\n",
        "    padding: 12px;\n",
        "    text-align: center;\n",
        "    transition: all 0.25s ease;\n",
        "}\n",
        ".veh-card.active {\n",
        "    background: rgba(245, 200, 66, 0.1);\n",
        "    border-color: var(--gold);\n",
        "    box-shadow: 0 0 0 2px rgba(245, 200, 66, 0.2);\n",
        "}\n",
        ".veh-card i { font-size: 22px; color: var(--gold-bright); }\n",
        ".veh-card .name { font-size: 12px; font-weight: 700; margin-top: 6px; color: var(--text-primary);}\n",
        ".veh-card .seats { font-size: 10px; color: var(--text-muted); margin-top: 2px;}\n",
        "\n",
        ".result-shell {\n",
        "    margin-top: 24px;\n",
        "    background: linear-gradient(135deg, rgba(10, 19, 48, 0.8) 0%, rgba(26, 38, 85, 0.9) 100%);\n",
        "    border: 1px solid var(--glass-border);\n",
        "    border-radius: 28px;\n",
        "    padding: 32px;\n",
        "    backdrop-filter: blur(20px);\n",
        "    box-shadow: 0 20px 60px rgba(0, 0, 0, 0.5), inset 0 1px 0 rgba(255, 255, 255, 0.06);\n",
        "    position: relative;\n",
        "    overflow: hidden;\n",
        "    animation: slideUp 0.5s cubic-bezier(0.16, 1, 0.3, 1);\n",
        "}\n",
        "@keyframes slideUp { from { opacity: 0; transform: translateY(16px);} to { opacity: 1; transform: translateY(0);} }\n",
        ".result-shell::before { content: ''; position: absolute; top: 0; left: 0; right: 0; height: 2px; background: var(--gold-grad);}\n",
        ".result-grid { display: grid; grid-template-columns: 1fr auto; gap: 24px; align-items: center; }\n",
        "\n",
        ".ai-pill {\n",
        "    display: inline-flex; align-items: center; gap: 8px;\n",
        "    background: linear-gradient(135deg, rgba(59, 130, 246, 0.15), rgba(96, 165, 250, 0.1));\n",
        "    border: 1px solid rgba(96, 165, 250, 0.4);\n",
        "    color: var(--blue-glow);\n",
        "    padding: 6px 14px; border-radius: 50px;\n",
        "    font-size: 11px; font-weight: 700; letter-spacing: 1px;\n",
        "    text-transform: uppercase;\n",
        "}\n",
        "\n",
        ".price-label { color: var(--text-muted); font-size: 13px; margin-top: 14px; letter-spacing: 0.5px;text-align: center; /* THÊM DÒNG NÀY */\n",
        "    width: 100%;        /* THÊM DÒNG NÀY */}\n",
        ".price-mega {\n",
        "    font-family: 'Playfair Display', serif;\n",
        "    font-size: 56px; font-weight: 900;\n",
        "    background: var(--gold-grad);\n",
        "    -webkit-background-clip: text; background-clip: text;\n",
        "    -webkit-text-fill-color: transparent;\n",
        "    line-height: 1.1; letter-spacing: -2px;\n",
        "    margin-top: 4px;\n",
        "    text-align: center; /* THÊM DÒNG NÀY */\n",
        "    width: 100%;        /* THÊM DÒNG NÀY */\n",
        "    display: block;\n",
        "}\n",
        ".price-currency { font-size: 22px; color: var(--gold); font-weight: 700; margin-left: 6px; }\n",
        "\n",
        ".confirm-btn {\n",
        "    background: var(--gold-grad);\n",
        "    color: var(--navy-900);\n",
        "    border: none; padding: 18px 36px; border-radius: 16px;\n",
        "    font-weight: 800; font-size: 14px; letter-spacing: 1.5px;\n",
        "    cursor: pointer;\n",
        "    box-shadow: 0 10px 30px rgba(245, 200, 66, 0.35);\n",
        "    transition: all 0.3s ease;\n",
        "    text-transform: uppercase;\n",
        "    font-family: 'Plus Jakarta Sans', sans-serif;\n",
        "    display: inline-flex; align-items: center; gap: 10px;\n",
        "}\n",
        ".confirm-btn:hover { transform: translateY(-3px); box-shadow: 0 16px 40px rgba(245, 200, 66, 0.5);}\n",
        "\n",
        ".meta-row {\n",
        "    margin-top: 24px; padding-top: 20px;\n",
        "    border-top: 1px solid rgba(255, 255, 255, 0.08);\n",
        "    display: flex; flex-wrap: wrap; gap: 24px;\n",
        "}\n",
        ".meta-item { display: flex; align-items: center; gap: 10px; }\n",
        ".meta-icon {\n",
        "    width: 38px; height: 38px; border-radius: 10px;\n",
        "    background: rgba(245, 200, 66, 0.1);\n",
        "    border: 1px solid rgba(245, 200, 66, 0.25);\n",
        "    display: flex; align-items: center; justify-content: center;\n",
        "    color: var(--gold-bright); font-size: 14px;\n",
        "}\n",
        ".meta-text .lbl { font-size: 11px; color: var(--text-muted); text-transform: uppercase; letter-spacing: 1px;}\n",
        ".meta-text .val { font-size: 15px; color: var(--text-primary); font-weight: 700; margin-top: 2px;}\n",
        "\n",
        ".empty-state {\n",
        "    text-align: center; padding: 50px 30px;\n",
        "    background: var(--glass);\n",
        "    border: 1px dashed var(--glass-border);\n",
        "    border-radius: 24px;\n",
        "    margin-top: 24px;\n",
        "}\n",
        ".empty-state i { font-size: 48px; color: var(--gold); margin-bottom: 16px; }\n",
        ".empty-state h3 { color: var(--text-primary); font-weight: 700; margin: 0; }\n",
        ".empty-state p { color: var(--text-muted); margin-top: 8px; }\n",
        "\n",
        ".map-wrap {\n",
        "    border-radius: 20px; overflow: hidden;\n",
        "    border: 1px solid var(--glass-border);\n",
        "    box-shadow: 0 10px 40px rgba(0, 0, 0, 0.4);\n",
        "}\n",
        "iframe { border-radius: 20px !important; }\n",
        "\n",
        "::-webkit-scrollbar { width: 10px; height: 10px; }\n",
        "::-webkit-scrollbar-track { background: var(--navy-900); }\n",
        "::-webkit-scrollbar-thumb { background: var(--navy-600); border-radius: 5px; }\n",
        "::-webkit-scrollbar-thumb:hover { background: var(--gold-deep); }\n",
        "</style>\n",
        "\"\"\", unsafe_allow_html=True)\n",
        "\n",
        "# ============================================================\n",
        "# 3. DỮ LIỆU CÁC LOẠI XE\n",
        "# ============================================================\n",
        "VEHICLES = {\n",
        "    \"Motorbike\": {\"icon\": \"fa-motorcycle\",   \"name\": \"Xe điện\",       \"seats\": \"1 chỗ\",     \"base\": 10000, \"km_rate\": 4000,  \"speed\": 2.5},\n",
        "    \"Car4\":      {\"icon\": \"fa-car\",          \"name\": \"Ô tô 4 chỗ\",   \"seats\": \"4 chỗ\",     \"base\": 25000, \"km_rate\": 11000, \"speed\": 2.8},\n",
        "    \"Car7\":      {\"icon\": \"fa-van-shuttle\",  \"name\": \"Ô tô 7 chỗ\",   \"seats\": \"7 chỗ\",     \"base\": 32000, \"km_rate\": 14000, \"speed\": 3.0},\n",
        "    \"Luxury\":    {\"icon\": \"fa-car-side\",     \"name\": \"Luxury Car\",   \"seats\": \"4 chỗ VIP\", \"base\": 30000, \"km_rate\": 13000, \"speed\": 2.5},\n",
        "}\n",
        "if 'vehicle' not in st.session_state:\n",
        "    st.session_state.vehicle = \"Motorbike\"\n",
        "def get_automated_demand():\n",
        "    now = datetime.now()\n",
        "    hour = now.hour\n",
        "    minute = now.minute\n",
        "    time_float = hour + minute / 60.0\n",
        "    weekday = now.weekday()  # 0 là Thứ 2, 6 là Chủ nhật\n",
        "\n",
        "    # 1. Giả lập Nhu cầu cơ bản theo giờ (Sử dụng hàm hình chuông - Bell Curve)\n",
        "    # Cao điểm sáng (7h30) và chiều (17h30)\n",
        "    morning_peak = 9.0 * np.exp(-((time_float - 7.5)**2) / (2 * 1.5**2))\n",
        "    evening_peak = 9.5 * np.exp(-((time_float - 17.5)**2) / (2 * 2.0**2))\n",
        "\n",
        "    demand_score = max(morning_peak, evening_peak)\n",
        "\n",
        "    # 2. Điều chỉnh theo ngày trong tuần\n",
        "    if weekday >= 5:  # Cuối tuần nhu cầu đi chơi dàn trải hơn\n",
        "        demand_score = max(demand_score, 7.0 if 10 <= hour <= 21 else 3.0)\n",
        "\n",
        "    # 3. Thêm một chút biến động ngẫu nhiên (Random nhẹ)\n",
        "    # Giả lập việc đôi khi có một nhóm sinh viên tan học sớm hoặc sự kiện\n",
        "    noise = np.random.uniform(-0.5, 0.5)\n",
        "\n",
        "    # Đảm bảo kết quả nằm trong khoảng [1, 10]\n",
        "    final_demand = round(max(1.0, min(10.0, demand_score + noise)), 1)\n",
        "    return final_demand\n",
        "# ============================================================\n",
        "# 4. FUZZY LOGIC\n",
        "# ============================================================\n",
        "@st.cache_resource\n",
        "def init_fuzzy():\n",
        "    distance = ctrl.Antecedent(np.arange(0, 51, 1), 'distance')\n",
        "    traffic = ctrl.Antecedent(np.arange(0, 11, 1), 'traffic')\n",
        "    weather = ctrl.Antecedent(np.arange(0, 11, 1), 'weather')\n",
        "    price = ctrl.Consequent(np.arange(0, 101, 1), 'price')\n",
        "    demand = ctrl.Antecedent(np.arange(0, 11, 1), 'demand')\n",
        "\n",
        "    distance.automf(3, names=['short', 'medium', 'long'])\n",
        "    traffic.automf(3, names=['low', 'medium', 'high'])\n",
        "    weather['good'] = fuzz.trimf(weather.universe, [0, 0, 5])\n",
        "    weather['bad'] = fuzz.trimf(weather.universe, [5, 10, 10])\n",
        "    price.automf(3, names=['low', 'medium', 'high'])\n",
        "    demand['low'] = fuzz.trapmf(demand.universe, [0, 0, 2, 4])\n",
        "    demand['medium'] = fuzz.trimf(demand.universe, [3, 5, 7])\n",
        "    demand['high'] = fuzz.trapmf(demand.universe, [6, 8, 10, 10])\n",
        "\n",
        "    rules = [\n",
        "    # Nhóm 1: Ưu tiên giảm giá khi Nhu cầu thấp (Bất kể kẹt xe hay không)\n",
        "    ctrl.Rule(demand['low'] & (traffic['low'] | traffic['medium']), price['low']),\n",
        "    ctrl.Rule(demand['low'] & traffic['high'], price['medium']),\n",
        "\n",
        "    # Nhóm 2: Nhu cầu trung bình (Giá ổn định)\n",
        "    ctrl.Rule(demand['medium'] & traffic['low'], price['low']),\n",
        "    ctrl.Rule(demand['medium'] & traffic['medium'], price['medium']),\n",
        "    ctrl.Rule(demand['medium'] & traffic['high'], price['high']),\n",
        "\n",
        "    # Nhóm 3: Nhu cầu cao (Tăng giá mạnh - Giờ cao điểm)\n",
        "    ctrl.Rule(demand['high'] & traffic['low'], price['medium']),\n",
        "    ctrl.Rule(demand['high'] & (traffic['medium'] | traffic['high']), price['high']),\n",
        "\n",
        "    # Nhóm 4: Trường hợp đặc biệt (Mưa + Nhu cầu cao = Giá cực cao)\n",
        "    ctrl.Rule(weather['bad'] & demand['high'], price['high']),\n",
        "    # Nhóm 5: Sự kết hợp giữa Thời tiết và Giao thông (Cực kỳ quan trọng)\n",
        "    # Trời mưa + Đường kẹt = Giá cao nhất (để gọi tài xế ra đường)\n",
        "    ctrl.Rule(weather['bad'] & traffic['high'], price['high']),\n",
        "\n",
        "    # Trời mưa + Nhu cầu trung bình = Giá vẫn nên cao\n",
        "    ctrl.Rule(weather['bad'] & demand['medium'], price['high']),\n",
        "\n",
        "    # Nhóm 6: Bảo vệ giá khi đường cực vắng\n",
        "    # Nếu đường rất vắng và nhu cầu cũng thấp thì chắc chắn giá phải rẻ nhất\n",
        "    ctrl.Rule(traffic['low'] & demand['low'], price['low']),\n",
        "\n",
        "    # Nhóm 7: Luật bù trừ\n",
        "    # Nếu đường kẹt nhưng nhu cầu cực thấp (ví dụ đêm khuya), giá chỉ nên ở mức trung bình\n",
        "    ctrl.Rule(traffic['high'] & demand['low'], price['medium'])\n",
        "]\n",
        "    return ctrl.ControlSystemSimulation(ctrl.ControlSystem(rules))\n",
        "\n",
        "sim = init_fuzzy()\n",
        "geolocator = Nominatim(user_agent=\"tnt_grab_pro_v6\")\n",
        "\n",
        "def get_address(lat, lon):\n",
        "    try:\n",
        "        location = geolocator.reverse((lat, lon), timeout=10)\n",
        "        return location.address if location else f\"{lat:.4f}, {lon:.4f}\"\n",
        "    except Exception:\n",
        "        return f\"{lat:.4f}, {lon:.4f}\"\n",
        "\n",
        "def get_smart_traffic(dist_km, start_coords, end_coords):\n",
        "    import random\n",
        "    from datetime import datetime\n",
        "    import math\n",
        "\n",
        "    now = datetime.now()\n",
        "    hour = now.hour\n",
        "    weekday = now.weekday()  # 0=Mon\n",
        "\n",
        "    # =========================\n",
        "    # 1. BASE THEO GIỜ\n",
        "    # =========================\n",
        "    # =========================\n",
        "    # 1. BASE THEO GIỜ (Cập nhật mới)\n",
        "    # =========================\n",
        "    if 7 <= hour <= 9:\n",
        "        base = 7.5\n",
        "    elif 11 <= hour <= 13:\n",
        "        base = 5.5\n",
        "    elif 14 <= hour <= 16:\n",
        "        base = 4.0\n",
        "    elif 17 <= hour <= 19:\n",
        "        base = 8.0 # Cao điểm gắt\n",
        "    elif 19 < hour <= 21:\n",
        "        base = 6.3\n",
        "    elif 22 <= hour or hour <= 4:\n",
        "        base = 1.5\n",
        "    else:\n",
        "        base = 4.5\n",
        "\n",
        "    # =========================\n",
        "    # 2. THEO NGÀY\n",
        "    # =========================\n",
        "    if weekday >= 5:  # cuối tuần\n",
        "        if 9 <= hour <= 21:\n",
        "            base += 1.0\n",
        "        else:\n",
        "            base -= 0.5\n",
        "\n",
        "\n",
        "    # =========================\n",
        "    # 3. THEO KHOẢNG CÁCH (Chỉnh lại: Khoảng cách xa không nên làm tăng mật độ)\n",
        "    # =========================\n",
        "    # Mật độ giao thông thường phụ thuộc vào địa điểm hơn là tổng quãng đường.\n",
        "    # Nên giảm bớt trọng số này.\n",
        "    if dist_km > 15:\n",
        "        base += 0.5\n",
        "    elif dist_km < 2:\n",
        "        base -= 0.5\n",
        "\n",
        "    # =========================\n",
        "    # 4. HIỆU ỨNG TRUNG TÂM TP (Quận 1) - Tối ưu lại\n",
        "    # =========================\n",
        "    center = (10.7769, 106.7009)\n",
        "    def calc_distance(a, b):\n",
        "        return math.sqrt((a[0]-b[0])**2 + (a[1]-b[1])**2)\n",
        "\n",
        "    d_start = calc_distance(start_coords, center)\n",
        "    d_end = calc_distance(end_coords, center)\n",
        "\n",
        "    # Thay vì cộng 0.7, hãy dùng hệ số để giá trị không bị vọt quá cao\n",
        "    if d_start < 0.05 or d_end < 0.05:\n",
        "        # Giới hạn: Nếu đã là giờ cao điểm (7.5) thì chỉ tăng nhẹ\n",
        "        if base >= 7.0:\n",
        "            base += 0.3\n",
        "        else:\n",
        "            base += 0.7\n",
        "\n",
        "    # =========================\n",
        "    # 5. THỜI TIẾT\n",
        "    # =========================\n",
        "    if st.session_state.get(\"rain_toggle\", False):\n",
        "        base += 1.5\n",
        "\n",
        "    # =========================\n",
        "    # 6. RANDOM THÔNG MINH\n",
        "    # =========================\n",
        "    noise = random.uniform(-0.8, 0.8)\n",
        "\n",
        "    traffic = base + noise\n",
        "\n",
        "    return round(min(10, max(1, traffic)), 1)\n",
        "\n",
        "# ============================================================\n",
        "# 5. SESSION STATE\n",
        "# ============================================================\n",
        "if 'start_coords' not in st.session_state: st.session_state.start_coords = [10.7769, 106.7009]\n",
        "if 'end_coords' not in st.session_state: st.session_state.end_coords = [10.8231, 106.6297]\n",
        "if 'start_addr' not in st.session_state: st.session_state.start_addr = \"Quận 1, TP.HCM\"\n",
        "if 'end_addr' not in st.session_state: st.session_state.end_addr = \"Quận Tân Bình, TP.HCM\"\n",
        "if 'vehicle' not in st.session_state: st.session_state.vehicle = \"Luxury\"\n",
        "# 1. Đoạn này đặt TRÊN Hero Header để lấy dữ liệu trước\n",
        "dist = 0\n",
        "try:\n",
        "    # Key API GraphHopper của bạn\n",
        "    url = f\"https://graphhopper.com/api/1/route?point={st.session_state.start_coords[0]},{st.session_state.start_coords[1]}&point={st.session_state.end_coords[0]},{st.session_state.end_coords[1]}&vehicle=car&key=79ebf81c-8a0b-4e39-8f89-f7805f154c98\"\n",
        "    res = requests.get(url).json()\n",
        "    if \"paths\" in res:\n",
        "        dist = res[\"paths\"][0][\"distance\"] / 1000 # Đổi sang km\n",
        "except:\n",
        "    dist = 0 # Nếu lỗi thì mặc định là 0\n",
        "\n",
        "# 2. Sau đó mới tới phần hiển thị Hero Header (nơi bạn dùng biến dist để tính tiền)\n",
        "# ... (Giữ nguyên phần Markdown/HTML của bạn ở đây) ...\n",
        "# ============================================================\n",
        "# 6. HERO HEADER\n",
        "# ============================================================\n",
        "auto_tf = get_smart_traffic(\n",
        "    dist,\n",
        "    st.session_state.start_coords,\n",
        "    st.session_state.end_coords\n",
        ")\n",
        "current_time = datetime.now().strftime(\"%H:%M\")\n",
        "# Bước 2: AI tự động tính toán nhu cầu khách hàng theo giờ\n",
        "auto_demand = get_automated_demand()\n",
        "\n",
        "# Bước 3: Lấy thời gian hiện tại để hiển thị lên giao diện\n",
        "current_time = datetime.now().strftime(\"%H:%M\")\n",
        "\n",
        "# Bước 4: Nạp tất cả vào \"Bộ não\" Logic mờ để tính toán\n",
        "sim.input['traffic'] = auto_tf\n",
        "sim.input['demand'] = auto_demand\n",
        "# Nếu bạn có nút check mưa, hãy thay True/False vào đây\n",
        "sim.input['weather'] = 8 if st.session_state.get('is_raining', False) else 2\n",
        "\n",
        "sim.compute()\n",
        "\n",
        "# Bước 5: Tính toán hệ số biến động giá (Surge)\n",
        "# 0.7 là mức tối thiểu (Giảm giá 30% khi vắng khách)\n",
        "surge = 0.8 + (sim.output['price'] / 120)\n",
        "surge = min(1.5, surge)\n",
        "sim.compute()\n",
        "v = VEHICLES[st.session_state.vehicle]\n",
        "    # Công thức chuẩn giống Grab\n",
        "if dist <= 2:\n",
        "    total = v['base']\n",
        "else:\n",
        "    total = v['base'] + (dist - 2) * v['km_rate']\n",
        "\n",
        "# Áp dụng surge\n",
        "    total *= surge\n",
        "# làm tròn đẹp\n",
        "final_price = max(0, round(total / 1000) * 1000)\n",
        "\n",
        "st.markdown(f\"\"\"\n",
        "<div class=\"hero-wrap\">\n",
        "  <div class=\"hero-content\">\n",
        "    <div>\n",
        "      <div class=\"hero-badge\"><span class=\"dot\"></span> AI POWERED · FUZZY LOGIC ENGINE</div>\n",
        "      <h1 class=\"hero-title\">TNT SMARTFARE <span style=\"color:#f8fafc;\"></span></h1>\n",
        "      <div class=\"hero-sub\"><i class=\"fa-solid fa-shield-halved\" style=\"color:#f5c842;\"></i> &nbsp; Hệ thống định vị thông minh · Tính cước phí mờ thời gian thực</div>\n",
        "    </div>\n",
        "    <div class=\"hero-stats\">\n",
        "      <div class=\"stat-item\">\n",
        "        <div class=\"stat-val\">{current_time}</div>\n",
        "        <div class=\"stat-lbl\"><i class=\"fa-regular fa-clock\"></i> Thời gian</div>\n",
        "      </div>\n",
        "      <div class=\"stat-item\">\n",
        "        <div class=\"stat-val\">{auto_tf}<span style=\"font-size:14px;color:#94a3b8;\">/10</span></div>\n",
        "        <div class=\"stat-lbl\"><i class=\"fa-solid fa-traffic-light\"></i> Mật độ</div>\n",
        "      </div>\n",
        "    </div>\n",
        "  </div>\n",
        "</div>\n",
        "\"\"\", unsafe_allow_html=True)\n",
        "\n",
        "# ============================================================\n",
        "# 7. LAYOUT CHÍNH\n",
        "# ============================================================\n",
        "# ============================================================\n",
        "# 7. LAYOUT CHÍNH\n",
        "# ============================================================\n",
        "if 'dist' not in locals(): dist = 0\n",
        "col_map, col_ctrl = st.columns([2.2, 1], gap=\"medium\")\n",
        "\n",
        "with col_ctrl:\n",
        "    st.markdown('<div class=\"panel-title\"><i class=\"fa-solid fa-route\"></i> Lộ trình của bạn</div>', unsafe_allow_html=True)\n",
        "    with st.container(border=True):\n",
        "        s_input = st.text_input(\"📍 Điểm đón\", value=st.session_state.start_addr, key=\"s_in\")\n",
        "        e_input = st.text_input(\"🏁 Điểm đến\", value=st.session_state.end_addr, key=\"e_in\")\n",
        "\n",
        "        col_b1, col_b2 = st.columns(2)\n",
        "        with col_b1:\n",
        "            if st.button(\"Tìm địa chỉ\", use_container_width=True, key=\"search_btn\"):\n",
        "                try:\n",
        "                    l1 = geolocator.geocode(s_input)\n",
        "                    l2 = geolocator.geocode(e_input)\n",
        "                    if l1:\n",
        "                        st.session_state.start_coords = [l1.latitude, l1.longitude]\n",
        "                        st.session_state.start_addr = l1.address\n",
        "                    if l2:\n",
        "                        st.session_state.end_coords = [l2.latitude, l2.longitude]\n",
        "                        st.session_state.end_addr = l2.address\n",
        "                    st.rerun()\n",
        "                except Exception:\n",
        "                    st.warning(\"Không tìm được địa chỉ.\")\n",
        "        with col_b2:\n",
        "            if st.button(\"Reset Map\", use_container_width=True, type=\"secondary\", key=\"reset_btn\"):\n",
        "                st.session_state.start_coords = [10.7769, 106.7009]\n",
        "                st.session_state.end_coords = [10.8231, 106.6297]\n",
        "                st.rerun()\n",
        "\n",
        "    st.markdown('<div class=\"panel-title\" style=\"margin-top:18px;\"><i class=\"fa-solid fa-car-rear\"></i> Chọn phương tiện</div>', unsafe_allow_html=True)\n",
        "    with st.container(border=True):\n",
        "        veh_keys = list(VEHICLES.keys())\n",
        "        idx = veh_keys.index(st.session_state.vehicle) if st.session_state.vehicle in veh_keys else 0\n",
        "        chosen = st.radio(\n",
        "            \"Loại xe\",\n",
        "            options=veh_keys,\n",
        "            format_func=lambda x: f\"{VEHICLES[x]['name']} · {VEHICLES[x]['seats']}\",\n",
        "            index=idx,\n",
        "            label_visibility=\"collapsed\",\n",
        "            key=\"vehicle_radio\"\n",
        "        )\n",
        "        st.session_state.vehicle = chosen\n",
        "\n",
        "        v_info = VEHICLES[chosen]\n",
        "        st.markdown(f'<div style=\"display:flex;align-items:center;gap:14px;padding:14px;background:rgba(245,200,66,0.08);border:1px solid rgba(245,200,66,0.3);border-radius:14px;margin-top:10px;\"><div style=\"width:50px;height:50px;border-radius:12px;background:rgba(245,200,66,0.15);display:flex;align-items:center;justify-content:center;\"><i class=\"fa-solid {v_info[\"icon\"]}\" style=\"font-size:24px;color:#ffd86b;\"></i></div><div><div style=\"color:#ffd86b;font-weight:700;font-size:15px;\">{v_info[\"name\"]}</div><div style=\"color:#94a3b8;font-size:12px;\">Mở cửa: {v_info[\"base\"]:,}đ • Mỗi km: {v_info[\"km_rate\"]:,}đ</div></div></div>', unsafe_allow_html=True)\n",
        "\n",
        "\n",
        "    st.markdown('<div class=\"panel-title\" style=\"margin-top:18px;\"><i class=\"fa-solid fa-sliders\"></i> Tùy chọn & Ưu đãi</div>', unsafe_allow_html=True)\n",
        "    with st.container(border=True):\n",
        "        is_raining = st.toggle(\"🌧️ Đang có mưa/bão\", value=False, key=\"rain_toggle\")\n",
        "\n",
        "        promo_code = st.text_input(\"🎟️ Mã giảm giá\", placeholder=\"Nhập mã giảm giá\", key=\"promo\").upper()\n",
        "        discount_val = 0\n",
        "        if promo_code == \"UEH\":\n",
        "            st.success(\"✅ Mã UEH: Giảm 20.000đ\")\n",
        "            discount_val = 20000\n",
        "        elif promo_code == \"LUONGVE\":\n",
        "            st.success(\"✅ Mã LUONGVE: Giảm 10%\")\n",
        "        elif promo_code != \"\":\n",
        "            st.warning(\"⚠️ Mã không hợp lệ.\")\n",
        "with col_map:\n",
        "    st.markdown('<div class=\"panel-title\"><i class=\"fa-solid fa-map-location-dot\"></i> Bản đồ trực tiếp</div>', unsafe_allow_html=True)\n",
        "\n",
        "    # Khởi tạo bản đồ\n",
        "    m = folium.Map(\n",
        "        location=st.session_state.start_coords,\n",
        "        zoom_start=13,\n",
        "        tiles=\"https://mt1.google.com/vt/lyrs=m&x={x}&y={y}&z={z}\",\n",
        "        attr=\"Google Maps\"\n",
        "    )\n",
        "\n",
        "    # Thêm Marker\n",
        "    folium.Marker(st.session_state.start_coords, tooltip=\"Điểm đón\", icon=folium.Icon(color='green', icon='play', prefix='fa')).add_to(m)\n",
        "    folium.Marker(st.session_state.end_coords, tooltip=\"Điểm đến\", icon=folium.Icon(color='red', icon='flag-checkered', prefix='fa')).add_to(m)\n",
        "\n",
        "    # TÍNH TOÁN LỘ TRÌNH VỚI GRAPHHOPPER\n",
        "    dist = 0\n",
        "    p1, p2 = st.session_state.start_coords, st.session_state.end_coords\n",
        "    try:\n",
        "        url = f\"http://router.project-osrm.org/route/v1/driving/{p1[1]},{p1[0]};{p2[1]},{p2[0]}?overview=full&geometries=geojson\"\n",
        "        res = requests.get(url, timeout=10).json()\n",
        "        if 'routes' in res and len(res['routes']) > 0:\n",
        "            route = res['routes'][0]\n",
        "            dist = route['distance'] / 1000\n",
        "            coords = [(p[1], p[0]) for p in route['geometry']['coordinates']]\n",
        "            folium.PolyLine(coords, color=\"#ffd86b\", weight=4, opacity=0.95).add_to(m)\n",
        "            m.fit_bounds([p1, p2])\n",
        "    except Exception:\n",
        "        pass\n",
        "\n",
        "    # HIỂN THỊ BẢN ĐỒ (Quan trọng: width=None để nó tự fill khung CSS)\n",
        "    st.markdown('<div class=\"map-wrap\">', unsafe_allow_html=True)\n",
        "    map_output = st_folium(m, height=500, width=None, key=\"tnt_map\")\n",
        "    st.markdown('</div>', unsafe_allow_html=True)\n",
        "\n",
        "    # XỬ LÝ CLICK CHUỘT (Sửa lỗi loop)\n",
        "    # 1. ÉP VỊ TRÍ VỀ VIỆT NAM TRONG HÀM TÌM KIẾM\n",
        "# 1. ÉP VỊ TRÍ VỀ VIỆT NAM TRONG HÀM TÌM KIẾM\n",
        "def get_address(lat, lon):\n",
        "    try:\n",
        "        # Thêm country_codes để giới hạn phạm vi tìm kiếm tại Việt Nam\n",
        "        location = geolocator.reverse((lat, lon), timeout=10, language='vi')\n",
        "        return location.address if location else f\"{lat:.4f}, {lon:.4f}\"\n",
        "    except Exception:\n",
        "        return f\"{lat:.4f}, {lon:.4f}\"\n",
        "\n",
        "# 2. KIỂM TRA CLICK CHUỘT THÔNG MINH (TRÁNH RERUN VÔ TẬN)\n",
        "if map_output and map_output.get('last_object_clicked'):\n",
        "    click_c = [map_output['last_object_clicked']['lat'], map_output['last_object_clicked']['lng']]\n",
        "\n",
        "    # Tính khoảng cách Euclidean đơn giản để xem người dùng có thực sự muốn đổi điểm không\n",
        "    d_start = math.sqrt((click_c[0]-st.session_state.start_coords[0])**2 + (click_c[1]-st.session_state.start_coords[1])**2)\n",
        "    d_end = math.sqrt((click_c[0]-st.session_state.end_coords[0])**2 + (click_c[1]-st.session_state.end_coords[1])**2)\n",
        "\n",
        "    threshold = 0.0001 # Một khoảng cách rất nhỏ\n",
        "    if d_start > threshold and d_end > threshold:\n",
        "        if d_start < d_end:\n",
        "            st.session_state.start_coords = click_c\n",
        "            st.session_state.start_addr = get_address(click_c[0], click_c[1])\n",
        "        else:\n",
        "            st.session_state.end_coords = click_c\n",
        "            st.session_state.end_addr = get_address(click_c[0], click_c[1])\n",
        "        st.rerun()\n",
        "\n",
        "# 3. CẢI TIẾN CÔNG THỨC GIÁ (GIỐNG GRAB/BE HƠN)\n",
        "# Giá = [Giá mở cửa + (Quãng đường - 2km) * Đơn giá] * Hệ số kẹt xe - Giảm giá\n",
        "if dist > 0:\n",
        "    base_fare = v['base'] if dist <= 2 else v['base'] + (dist - 2) * v['km_rate']\n",
        "    # Surge chuẩn từ 1.0 đến 1.8 tùy vào kết quả AI\n",
        "    ai_surge = 1.0 + (sim.output['price'] / 100) * 0.8\n",
        "\n",
        "    total = base_fare * ai_surge\n",
        "    current_discount = st.session_state.get('discount_value', 0)\n",
        "    # Áp dụng mã giảm giá cuối cùng\n",
        "    if promo_code == \"LUONGVE\":\n",
        "        total *= 0.9\n",
        "    else:\n",
        "        total -= current_discount\n",
        "\n",
        "\n",
        "    final_price = max(0, round(total / 1000) * 1000)\n",
        "    eta = max(1, int(dist * v['speed']))\n",
        "\n",
        "    weather_icon = \"fa-cloud-showers-heavy\" if is_raining else \"fa-sun\"\n",
        "    weather_text = \"Mưa/Bão\" if is_raining else \"Trời tốt\"\n",
        "    promo_display = promo_code if promo_code else \"Không có\"\n",
        "    st.markdown(f\"\"\"\n",
        "    <div class=\"result-shell\">\n",
        "      <div class=\"result-grid\">\n",
        "        <div>\n",
        "          <span class=\"ai-pill\"><i class=\"fa-solid fa-microchip\"></i> AI ANALYSIS · MẬT ĐỘ {auto_tf}/10 · HỆ SỐ x{surge:.2f}</span>\n",
        "          <div class=\"price-label\">Tổng cước phí dự kiến</div>\n",
        "          <div class=\"price-mega\">{final_price:,}<span class=\"price-currency\">VNĐ</span></div>\n",
        "        </div>\n",
        "      </div>\n",
        "      <div class=\"meta-row\">\n",
        "        <div class=\"meta-item\">\n",
        "          <div class=\"meta-icon\"><i class=\"fa-solid {v['icon']}\"></i></div>\n",
        "          <div class=\"meta-text\"><div class=\"lbl\">Phương tiện</div><div class=\"val\">{v['name']}</div></div>\n",
        "        </div>\n",
        "        <div class=\"meta-item\">\n",
        "          <div class=\"meta-icon\"><i class=\"fa-solid fa-route\"></i></div>\n",
        "          <div class=\"meta-text\"><div class=\"lbl\">Quãng đường</div><div class=\"val\">{dist:.1f} km</div></div>\n",
        "        </div>\n",
        "        <div class=\"meta-item\">\n",
        "          <div class=\"meta-icon\"><i class=\"fa-regular fa-clock\"></i></div>\n",
        "          <div class=\"meta-text\"><div class=\"lbl\">Thời gian</div><div class=\"val\">{eta} phút</div></div>\n",
        "        </div>\n",
        "        <div class=\"meta-item\">\n",
        "          <div class=\"meta-icon\"><i class=\"fa-solid {weather_icon}\"></i></div>\n",
        "          <div class=\"meta-text\"><div class=\"lbl\">Thời tiết</div><div class=\"val\">{weather_text}</div></div>\n",
        "        </div>\n",
        "        <div class=\"meta-item\">\n",
        "          <div class=\"meta-icon\"><i class=\"fa-solid fa-ticket\"></i></div>\n",
        "          <div class=\"meta-text\"><div class=\"lbl\">Mã ưu đãi</div><div class=\"val\">{promo_display}</div></div>\n",
        "        </div>\n",
        "      </div>\n",
        "    </div>\n",
        "    \"\"\", unsafe_allow_html=True)\n",
        "    st.markdown(\"\"\"\n",
        "    <div style=\"text-align: center; margin-top: 20px;\">\n",
        "        <button class=\"confirm-btn\" style=\"width: 100%; justify-content: center;\">\n",
        "            <i class=\"fa-solid fa-check-double\"></i> XÁC NHẬN ĐẶT XE\n",
        "        </button>\n",
        "    </div>\n",
        "\"\"\", unsafe_allow_html=True)\n",
        "else:\n",
        "    st.markdown(\"\"\"\n",
        "    <div class=\"empty-state\">\n",
        "      <i class=\"fa-solid fa-location-crosshairs\"></i>\n",
        "      <h3>Chào mừng đến với TNT SMARTFARE 💎</h3>\n",
        "      <p>Hãy kéo Marker trên bản đồ hoặc nhập địa chỉ điểm đón và điểm đến để bắt đầu tính cước phí thông minh.</p>\n",
        "    </div>\n",
        "    \"\"\", unsafe_allow_html=True)\n",
        "\n",
        "# ============================================================\n",
        "# 9. FOOTER\n",
        "# ============================================================\n",
        "st.markdown(\"\"\"\n",
        "<div style=\"text-align:center; margin-top:40px; padding:20px; color:#94a3b8; font-size:12px; letter-spacing:1px;\">\n",
        "  <i class=\"fa-solid fa-gem\" style=\"color:#f5c842;\"></i>\n",
        "  &nbsp; TNT SMARTFARE · POWERED BY FUZZY LOGIC &nbsp;·&nbsp; © 2026\n",
        "</div>\n",
        "\"\"\", unsafe_allow_html=True)"
      ]
    }
  ]
}
